services:
  - type: web
    name: onboarding-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ONBOARDING_CHAT_ID
        value: "-5102890643"
      - key: ALLOWED_CREATORS
        value: "7294861370"
      - key: ADMIN_IDS
        value: "7294861370"
      - key: DB_URL
        value: "sqlite+aiosqlite:///./data/onboarding.db"
      - key: TIMEZONE
        value: "Europe/London"
